name: tiled

# micromamba create -n tiled -f environment.yml -y
# micromamba activate tiled

channels:
  - conda-forge
  - defaults

dependencies:
  - python >=3.8
  - alembic
  - appdirs
  - cachey
  - databroker
  - h5py
  - hdf5plugin
  - httpx
  - ipython
  - jmespath
  - matplotlib
  - orjson
  - pandas
  - pip
  - punx
  - pyarrow
  - pycrypto
  - python-jose
  - spec2nexus
  - sqlalchemy
  - typer
  - uvicorn
  - watchgod

  - pip:
    - tiled
    # old version: 2.1
    # - https://raw.githubusercontent.com/EPICS-synApps/utils/master/mdaPythonUtils/mdalib-2013.post2-py2.py3-none-any.whl
    # new version: 2.1.1
    - https://raw.githubusercontent.com/EPICS-synApps/utils/master/mdaPythonUtils/mdalib-2022.post9-py2.py3-none-any.whl
